package org.hbird.transport.packetarchive;

public class Packet extends PacketKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column packet.packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    private byte[] packet;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column packet.packet
     *
     * @return the value of packet.packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public byte[] getPacket() {
        return packet;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column packet.packet
     *
     * @param packet the value for packet.packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public void setPacket(byte[] packet) {
        this.packet = packet;
    }
}