package com.logica.hummingbird.packetarchive;

import java.sql.SQLException;
import java.util.List;

import com.logica.hummingbird.packetarchive.Packet;
import com.logica.hummingbird.packetarchive.PacketExample;
import com.logica.hummingbird.packetarchive.PacketKey;

public interface PacketDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int countByExample(PacketExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int deleteByExample(PacketExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int deleteByPrimaryKey(PacketKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    void insert(Packet record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    void insertSelective(Packet record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    List selectByExampleWithBLOBs(PacketExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    List selectByExampleWithoutBLOBs(PacketExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    Packet selectByPrimaryKey(PacketKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int updateByExampleSelective(Packet record, PacketExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int updateByExampleWithBLOBs(Packet record, PacketExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int updateByExampleWithoutBLOBs(Packet record, PacketExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int updateByPrimaryKeySelective(Packet record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table packet
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    int updateByPrimaryKey(Packet record) throws SQLException;
}