package com.logica.hummingbird.parameterarchive;

import java.sql.SQLException;
import java.util.List;

import com.logica.hummingbird.parameterarchive.Parameter;
import com.logica.hummingbird.parameterarchive.ParameterExample;
import com.logica.hummingbird.parameterarchive.ParameterKey;

public interface ParameterDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    int countByExample(ParameterExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    int deleteByExample(ParameterExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    int deleteByPrimaryKey(ParameterKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    void insert(Parameter record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    void insertSelective(Parameter record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    List selectByExample(ParameterExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    Parameter selectByPrimaryKey(ParameterKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    int updateByExampleSelective(Parameter record, ParameterExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    int updateByExample(Parameter record, ParameterExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    int updateByPrimaryKeySelective(Parameter record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table parameter
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    int updateByPrimaryKey(Parameter record) throws SQLException;
}