package com.logica.hummingbird.parameterarchive;

import java.util.Date;

public class ParameterKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parameter.onboard_creation_time
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    private Date onboardCreationTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parameter.onground_reception_time
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    private Date ongroundReceptionTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parameter.parameter_id
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    private Long parameterId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parameter.onboard_creation_time
     *
     * @return the value of parameter.onboard_creation_time
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public Date getOnboardCreationTime() {
        return onboardCreationTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parameter.onboard_creation_time
     *
     * @param onboardCreationTime the value for parameter.onboard_creation_time
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public void setOnboardCreationTime(Date onboardCreationTime) {
        this.onboardCreationTime = onboardCreationTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parameter.onground_reception_time
     *
     * @return the value of parameter.onground_reception_time
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public Date getOngroundReceptionTime() {
        return ongroundReceptionTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parameter.onground_reception_time
     *
     * @param ongroundReceptionTime the value for parameter.onground_reception_time
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public void setOngroundReceptionTime(Date ongroundReceptionTime) {
        this.ongroundReceptionTime = ongroundReceptionTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parameter.parameter_id
     *
     * @return the value of parameter.parameter_id
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public Long getParameterId() {
        return parameterId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parameter.parameter_id
     *
     * @param parameterId the value for parameter.parameter_id
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public void setParameterId(Long parameterId) {
        this.parameterId = parameterId;
    }
}