package com.logica.hummingbird.parameterarchive;

public class Parameter extends ParameterKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parameter.packet_id
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    private Long packetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column parameter.Value
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    private Float value;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parameter.packet_id
     *
     * @return the value of parameter.packet_id
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public Long getPacketId() {
        return packetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parameter.packet_id
     *
     * @param packetId the value for parameter.packet_id
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public void setPacketId(Long packetId) {
        this.packetId = packetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column parameter.Value
     *
     * @return the value of parameter.Value
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public Float getValue() {
        return value;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column parameter.Value
     *
     * @param value the value for parameter.Value
     *
     * @ibatorgenerated Tue Jan 12 00:04:48 CET 2010
     */
    public void setValue(Float value) {
        this.value = value;
    }
}