package com.logica.hummingbird.packetarchive;

import java.util.Date;

public class PacketKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column packet.onboard_creation_time
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    private Date onboardCreationTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column packet.onground_reception_time
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    private Date ongroundReceptionTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column packet.packet_id
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    private Long packetId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column packet.onboard_creation_time
     *
     * @return the value of packet.onboard_creation_time
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public Date getOnboardCreationTime() {
        return onboardCreationTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column packet.onboard_creation_time
     *
     * @param onboardCreationTime the value for packet.onboard_creation_time
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public void setOnboardCreationTime(Date onboardCreationTime) {
        this.onboardCreationTime = onboardCreationTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column packet.onground_reception_time
     *
     * @return the value of packet.onground_reception_time
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public Date getOngroundReceptionTime() {
        return ongroundReceptionTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column packet.onground_reception_time
     *
     * @param ongroundReceptionTime the value for packet.onground_reception_time
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public void setOngroundReceptionTime(Date ongroundReceptionTime) {
        this.ongroundReceptionTime = ongroundReceptionTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column packet.packet_id
     *
     * @return the value of packet.packet_id
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public Long getPacketId() {
        return packetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column packet.packet_id
     *
     * @param packetId the value for packet.packet_id
     *
     * @ibatorgenerated Mon Jan 11 12:06:07 CET 2010
     */
    public void setPacketId(Long packetId) {
        this.packetId = packetId;
    }
}